# Generated by Django 2.2 on 2019-04-16 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='ggirlname',
            new_name='ggirlnum',
        ),
    ]
